### PR TITLE
Provide a option to choose Node.js directory

### PR DESCRIPTION
**Pull request by w1da0**
## What is the purpose of the change 
Provide a option to choose Node.js directory and to avoid "env: node: No such file or directory" (#48). 

brida with node js path

### CODE REVIEW

**Comment by federicodotta** [comment]
Hi @w1da0,

thank you for the pull request. I will look at it as soon as possibile.

Meanwhile, are you using a Mac? Because other users that suffer from the issue of the Node.js path solved the issue in this way:
https://dani.gg/467-add-usr-local-bin-to-the-path-variable-on-mac-os/. Can you please try also this solution?

Thank you.

Federico

**Comment by w1da0** [comment]
Hi @federicodotta 

thank you for your reply. 

I tried it that you mentioned, and add my node.js' path(`usr/local/bin`) to `PATH`, but it dosen't worked for me on my MacBook Pro(Big Sur v11.2.3). 

Then i guess if there are any limitations on the Java library `Runtime.getRuntime().exec()`, so i tried to pick up your code to a single Java program to  execute the command:
```
/Users/x/node_modules/.bin/frida-compile -x -o /Users/x/Tools/brida/JS/bridaGeneratedCompiledOutput.js /Users/x/Tools/brida/JS/brida.js
``` 
```Java
    public static void main(String[] args) {
        String result = ExecuteCmd();
        System.out.println(result);
    }

    public static String ExecuteCmd() {
        Runtime rt = Runtime.getRuntime();

        String[] fridaCompileCommand = new String[]{
                "/Users/x/node_modules/.bin/frida-compile",
                "-x", "-o",
                "/Users/x/Tools/brida/JS/bridaGeneratedCompiledOutput.js",
                "/Users/x/Tools/brida/JS/brida.js"
        };

        Process processCompilation = null;
        try {
            processCompilation = rt.exec(fridaCompileCommand);
        } catch (IOException e) {
            e.printStackTrace();
            return "failed";
        }

        return "succ";
    }
```
 it's worked, so i further confirmed that the node.js path is in `PATH`.

But i don’t know why burp can’t be recognized it. 

If you have some other ideas, please tell me , I will tried it .

Thank you.

w1dao

**Comment by federicodotta** [comment]
Hi @w1da0,

unfortunately that is the only method that I know, but I tried it only till OSX 10 (and I haven't an OSX 11).

Another post that explains that method is this one:
https://github.com/ersiner/osx-env-sync/issues/1#issuecomment-230053839

A question. Have you rebooted after executing the command "sudo launchctl config user path $PATH"? Because it seems to be necessary.

Thank you a lot for your help.

Federico

**Comment by w1da0** [comment]
Hi @federicodotta,

It's amazing, the method worked.

First execute the command `sudo launchctl config user path $PATH`, then reboot. 

Yes, as you said, the step of `reboot` is necessary. 

Because i execute the command `launchctl procinfo` before reboot, it's show `PATH => /usr/bin:/bin:/usr/sbin:/sbin`.

And after I rebooted, execute the command `launchctl procinfo` again, it's show all the path i had added to `PATH`.

Most importantly, _Brida_ works perfectly now.

Thank you.

w1da0

**Comment by federicodotta** [comment]
Hi @w1da0 

Perfect, thank you! I will update the wiki in order to clarify the procedure for Mac users.

Thank you for your precious help and for your feedback with OSX 11!

Federico

**Pull request closed without merging**
